# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88843c9d9e9c31b52f9bea9f004c0021a65fbbba27aa309d9b650ae7e4af9def4070a0e3c625a3d4aecc5eff01b741c91e648320237a33bdc47e87c63341b17

test:
  secret_key_base: 33b854b0c2c4b5f45f2668099f7334310a0510aa7d8a0867f45f7b746d1a78ae337e89534079ac11fffdd618d392dfc30861c16fe294746a1935a878e6934c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
